### ISSUE TITLE
performKick function is called twice when player logs in gmisland

### ISSUE THREAD

**Issue by 0xCiBeR** [55Honey/Acore_Zonecheck#5]
Hey, for some reason performKick function is being called twice in a row when a player "logs in" a forbidden zone.

To test:
1.) Remove all forbidden zones except gmisland and add a log line
2.) Teleport normal player to gmisland
3.) Re-log that same player that got kicked in the island
4.) Observe how he is kicked and function is called twice

**Comment by 55Honey** [comment]
The source of this is, that the function to check for the player's zone/area is called 1) OnLogin and 2)OnUpdateZone.
Apparently the core fires the update-zone-event as well, since it changes from nothing to - in this case - the id of GM island.

**Comment by 55Honey** [comment]
@0xCiBeR i don't see a reason to change the behaviour. Consider it a safety measure. There's no harm done it doing this check once too often. It's not costly.
